name: Triggered Scrape

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'GitHub organization name'
        required: false
        default: 'vercel'
      repo_limit:
        description: 'Number of repositories to fetch'
        required: false
        default: '30'
      pr_limit:
        description: 'Number of pull requests to fetch per repository'
        required: false
        default: '30'
      max_retries:
        description: 'Maximum number of retries for failed requests'
        required: false
        default: '3'
      thread_count:
        description: 'Number of threads to use for processing'
        required: false
        default: '4'

jobs:
  scrape:
    runs-on: macos-latest

    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      PG_DATABASE: github_scraper_test
      PG_USERNAME: ${{ secrets.PG_USERNAME }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: localhost
      PG_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'

      - name: Install PostgreSQL
        run: |
          brew install postgresql@15
          brew services start postgresql@15
          createdb github_scraper_test

      - name: Install dependencies
        run: bundle install

      - name: Setup database
        run: |
          bundle exec rake db:drop
          bundle exec rake db:create
          bundle exec rake db:migrate

      - name: Run scraper
        run: |
          bundle exec ruby app.rb \
            --org ${{ inputs.org }} \
            --repo-limit ${{ inputs.repo_limit }} \
            --pr-limit ${{ inputs.pr_limit }} \
            --max-retries ${{ inputs.max_retries }} \
            --threads ${{ inputs.thread_count }}
